import { SnapkitProvider } from "@snapkit-studio/react";

import "../global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SnapkitProvider organizationName="snapkit">{children}</SnapkitProvider>
      </body>
    </html>
  );
}
